[theme]
name = "space-villain"

[icons]
name = "material-nf"

[[block]]
block = "time"
format = "%a %b %d %Y %r"
timezone = "US/Eastern"

[[block]]
block = "custom"
command = "curl -s 'https://wttr.in/New-York-City?format=1&u' | sed 's/  //'"
interval = 600

[[block]]
block = "sound"

[[block]]
block = "music"

[[block]]
block = "battery"
full_format = " {percentage}"
interval = 10

[[block]]
block = "custom"
command = "echo  GPU $(nvidia-smi --query-gpu=gpu_name,memory.used --format=csv,noheader | sed 's/,/\\ /')"
interval = 1

[[block]]
block = "disk_space"
format = " {icon} {used}/{total} ({available} free) "

[[block]]
block = "memory"
interval = 5

[[block]]
block = "cpu"
format = "{barchart} {utilization}"
interval = 1

[[block]]
block = "custom"
command = "echo `uname` `uname -r | tr - . | cut -d. -f1-2`"
interval = "once"
