# i3status-rust configuration file
# by David Oniani <onianidavid@gmail.com>
# MIT License

[theme]
theme = "space-villain"

[icons]
icons = "material-nf"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %b %d %Y %r') "
interval = 1
timezone = "US/Eastern"

[[block]]
block = "custom"
command = "curl -s 'https://wttr.in/Brooklyn?format=2&u'"
interval = 600

[[block]]
block = "sound"

[[block]]
block = "music"

[[block]]
block = "disk_space"

[[block]]
block = "memory"
interval = 1

[[block]]
block = "cpu"
format = "$barchart $utilization"
interval = 1

[[block]]
block = "battery"
interval = 1
