[theme]
name = "space-villain"

[icons]
name = "material-nf"

[[block]]
block = "time"
format = "%a %b %d %Y %r"
interval = 1
timezone = "US/Eastern"

[[block]]
block = "custom"
command = "curl -s 'https://wttr.in/New-York-City?format=2&u'"
interval = 600

[[block]]
block = "sound"

[[block]]
block = "music"

[[block]]
block = "disk_space"

[[block]]
block = "memory"
interval = 1

[[block]]
block = "cpu"
format = "{barchart} {utilization}"
interval = 1

[[block]]
block = "nvidia_gpu"
label = "Quadro T1000"
interval = 1

[[block]]
block = "battery"
full_format = "{percentage}"
interval = 1

[[block]]
block = "networkmanager"
device_format = "{icon}"
on_click = "kitty nmtui"
